name: Inattv JSON Generator

on:
  schedule:
    - cron: "*/4 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run scraper
        run: |
          python pygoals.py

      # 🔐 SSH KEY KUR
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_B64 }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # 📤 JSON'U SUNUCUYA GÖNDER
      - name: Upload inattv.json to server
        run: |
          scp -i ~/.ssh/id_ed25519 \
              -P ${{ secrets.SSH_PORT }} \
              inattv.json \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/u719601221/domains/selbuk.site/public_html/1/inattv.json
