name: Inattv JSON Generator

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: pip install requests beautifulsoup4

      - name: Run script
        run: python pygoals.py

      - name: Upload inattv.json via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 82.29.189.156
          username: u719601221.selbuk.site
          password: ...Mert...123...
          port: 21
          protocol: ftp
          security: loose
          timeout: 60000
          local-dir: ./
          server-dir: /public_html/1
          exclude: |
            **
            !inattv.json
