name: Inattv M3U Generator

on:
  schedule:
    - cron: "*/5 * * * *"   # 5 dakikada 1
  workflow_dispatch:       # Elle çalıştırma

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu çek
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Paketleri kur
        run: |
          pip install -r requirements.txt

      - name: Scripti çalıştır
        run: |
          python pygoals.py

      - name: Değişiklik varsa commit et
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add inattv.m3u
          git diff --cached --quiet || git commit -m "Auto update inattv.m3u"

      - name: Push
        run: |
          git push
